### ISSUE TITLE
[Question] Inquiry on how to build "sysvk / Vulkan WSI Layer" in PRoot-Distro Linux environment

### ISSUE THREAD

**Issue by hansm629** [xMeM/vulkan-wsi-layer#2]
hello. sir

I am using the dri3 patch you made very well.
Then, I recently found out that sir also created the `Vulkan WSI Layer`.
This is how I came to inquire.

I would like to use `Android Host Vulkan driver` in `PRoot Linux` environment through `sysvk & Vulkan WSI Layer` in `PRoot-Distro Debian` environment.

Host Device is Galaxy S24+ Exynos2400 model.
The Xclipse 940 GPU of Exynos2400 is a custom 6WGP (12CU) based on AMD RDNA3.
It has the same specifications as AMD 7840U.

PRoot-Distro in Debian12 environment
I'd like to see how well it works with sysvk and the Vulkan WSI Layer.

**Q1. How to build sysvk & Vulkan WSI Layer in PRoot-Distro Debian environment**
I'm curious about the dependency packages needed for a compile build, and I'm curious about the compile build procedure.

**Q2. Environment variables applied to the Termux-X11 environment**
I'm curious about the environment variables that make it work in Termux-X11 environment after compilation build.

**Q3. mesa zink environment variable**
I'm curious about the environment variable that enables zink. I think I need to do something different from turnip. Is what I perceived correct?

Thanks to your hard work, many users will be able to enjoy significant performance improvements in Termux.

I am always grateful. 👍

**Comment by xMeM** [comment]
Not available in chroot/proot because they use gnu libc and the Android driver link with bionic libc.

**Comment by hansm629** [comment]
@xMeM 
Oh, that's really sad...

So, in a proot/chroot environment, is the only realistic GPU acceleration for SoCs rather than Snapdragon series only virgl?

**Comment by xMeM** [comment]
For newer mali gpu, you can try Venus, Performance should be better than virgl.

**Comment by hansm629** [comment]
> For newer mali gpu, you can try Venus, Performance should be better than virgl.

@xMeM 
That's good news.
Could I try another GPU?

If  Xclipse GPU is about the same as RAVD, I expect it to work.

Come to think of it, I heard that Venus is not compatible with mesa zink yet...

Is what I perceived correct?

**Comment by hansm629** [comment]
@xMeM 
hello.
In Termux native XFCE environment (host device: Galaxy S24+ Exynos2400)
I want to test the `WSI Layer`.

Where can I download related packages?

https://packages-cf.termux.dev/apt/termux-main
Can I download it from the repo above?

`vulkan-loader-generic`
`vulkan-header`

Is it correct to install two packages?

I am wondering if there is anything that needs to be set separately after that.
What are the environment variables used with `zink`?
