### ISSUE TITLE
"mesa-vulkan-icd-wrapper" GALLIUM_DRIVER cannot be used concurrently issue

### ISSUE THREAD

**Issue by hansm629** [xMeM/vulkan-wsi-layer#27]
@xMeM 

https://github.com/xMeM/termux-packages/actions/runs/11743740473
`mesa-vulkan-icd-wrapper-dbg_24.2.5-7_aarch64.deb`

Finally, from the latest version, `DXVK` is work on the `Xclipse series GPU`!

Thank you so much, Sir, for your development efforts amidst your busy schedule!

Most SoC GPUs still don’t work perfectly or at all with `Zink` on `mesa-24.x.x`.

For programs that currently have usability issues, I’m planning to use the `GALLIUM_DRIVER=virpipe` environment variable until `Zink` usability improves. However, in the latest build, the `GALLIUM_DRIVER` environment variable does not work. Even with the `virgl server` running, `glmark2` always runs with `Zink` when using the command below.

```
~$ GALLIUM_DRIVER=virpipe glmark2
``` 

Could you possibly enable the `GALLIUM_DRIVER` environment variable to work in the next build?

**Comment by xMeM** [comment]
Add `LIBGL_KOPPER_DISABLE=1` environment variable

**Comment by hansm629** [comment]
@xMeM 
It works!
Thank You! :)

```
~$ LIBGL_KOPPER_DISABLE=1 GALLIUM_DRIVER=virpipe glmark2
** GLX does not support GLX_EXT_swap_control or GLX_MESA_swap_control!
** Failed to set swap interval. Results may be bounded above by refresh rate.
=======================================================
    glmark2 2023.01
=======================================================
    OpenGL Information
    GL_VENDOR:      Mesa
    GL_RENDERER:    virgl (ANGLE (Samsung Electronics Co. Ltd., Vulkan 1.3.264 ...)
    GL_VERSION:     4.6 (Compatibility Profile) Mesa 24.2.6
    Surface Config: buf=32 r=8 g=8 b=8 a=8 depth=32 stencil=0 samples=0
    Surface Size:   800x600 windowed
=======================================================
** GLX does not support GLX_EXT_swap_control or GLX_MESA_swap_control!
** Failed to set swap interval. Results may be bounded above by refresh rate.
[build] use-vbo=false: FPS: 123 FrameTime: 8.131 ms

```
