### ISSUE TITLE
"mesa-vulkan-icd-wrapper" issues Reporting 2024-11-11 (GPU : ARM Mali-G57) 

### ISSUE THREAD

**Issue by Githubpradip** [xMeM/vulkan-wsi-layer#28]
@xMeM 
![Screenshot_2024-11-11-13-22-44-739_com termux](https://github.com/user-attachments/assets/bae17819-cfae-43eb-b3ad-2d184c2cfd71)
I have poco m4 (Mali-G57)where 
I launched vulkaninfo in termux with LD_LIBRARY_PATH=$PREFIX/lib but that doesn't work 
I used this mesa-vullan-icd-wrapper
https://github.com/xMeM/termux-packages/actions/runs/11756819746
Pls give me package for it because I can't make packages for termux

**Comment by Trass3r** [comment]
Don't mess with the LD_LIBRARY_PATH. I personally only needed that for that alex hangover package.
