### ISSUE TITLE
"mesa-vulkan-icd-wrapper" issues Reporting 2024-11-16 (wsi_common_x11.c:1915)

### ISSUE THREAD

**Issue by hansm629** [xMeM/vulkan-wsi-layer#34]
@xMeM 
This issue is occurring consistently across all `SoC GPUs`.
For demos like vkcube or glxgears, which allow resizing the window, the following message is displayed when the window size is adjusted.

Could this log be intentional?😮

If everything is functioning as intended, it seems like a log that doesn’t need to be displayed. What do you think?

https://github.com/xMeM/termux-packages/actions/runs/11801252552
- Package: `mesa-vulkan-icd-wrapper-dbg_24.2.5-8_aarch64.deb`

**`../src/src/vulkan/wsi/wsi_common_x11.c:1915: Swapchain status changed to VK_SUBOPTIMAL_KHR`**

```
~$ vkcube
Selected WSI platform: xcb
Selected GPU 0: Samsung Xclipse 940, type: IntegratedGpu
../src/src/vulkan/wsi/wsi_common_x11.c:1915: Swapchain status changed to VK_SUBOPTIMAL_KHR
../src/src/vulkan/wsi/wsi_common_x11.c:1915: Swapchain status changed to VK_SUBOPTIMAL_KHR

~$ glxgears
6343 frames in 5.0 seconds = 720.442 FPS
6183 frames in 5.0 seconds = 658.590 FPS
Selected GPU 0: Samsung Xclipse 940, type: IntegratedGpu
../src/src/vulkan/wsi/wsi_common_x11.c:1915: Swapchain status changed to VK_SUBOPTIMAL_KHR

```

**Comment by xMeM** [comment]
Because this is a debug build.

**Comment by hansm629** [comment]
@xMeM 
Aha! I understand what you mean.😀
