### ISSUE TITLE
"mesa-vulkan-icd-wrapper" issues Reporting 2024-11-16 (mesa-24.2.6 Zink)

### ISSUE THREAD

**Issue by hansm629** [xMeM/vulkan-wsi-layer#35]
@xMeM 
I have compiled a summary of the issues occurring in `mesa Zink` for each `SoC GPU`.

If there are any issues that cannot be fixed due to limitations of the `Android host Vulkan driver` rather than being related to `mesa-vulkan-icd-wrapper`, please let me know, and I will exclude them from the issue list.

Please review.😃

https://github.com/xMeM/termux-packages/actions/runs/11801252552
https://github.com/xMeM/termux-packages/actions/runs/11615462635

- **Package**: `mesa-vulkan-icd-wrapper-dbg_24.2.5-8_aarch64.deb`, `mesa_24.2.6-1_aarch64.deb`

## Qualcomm Adreno 6xx series GPU

- [ ] **Zink not work issue**

Zink does not work, and the following failure message is displayed.
The test results are `Adreno 650 GPU`.

<details><summary>failed message list</summary>
<p>

```
$ MESA_LOADER_DRIVER_OVERRIDE=zink glxinfo -B
name of display: :1.0
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
Error: couldn't find RGB GLX visual or fbconfig
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
``` 
```
$ MESA_LOADER_DRIVER_OVERRIDE=zink glmark2
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
Error: glXChooseFBConfig() failed
Error: Error: Couldn't get GL visual config!
Error: main: Could not initialize canvas
``` 
```
$ MESA_LOADER_DRIVER_OVERRIDE=zink blender
Warning: Falling back to the standard locale ("C")
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
Error! Unsupported graphics card or driver.
A graphics card and driver with support for OpenGL 3.3 or higher is required.
The program will now close.
``` 
```
$ MESA_LOADER_DRIVER_OVERRIDE=zink shotcut
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
Aborted
``` 
```
MESA_LOADER_DRIVER_OVERRIDE=zink kdenlive
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QColorSpace(), profile  QSurfaceFormat::NoProfile)
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
glx: failed to create drisw screen
failed to load driver: zink
Could not initialize GLX
Aborted
``` 

</p>
</details> 

## Qualcomm Adreno 7xx series GPU

- [ ] **glmark2 & glamrk2-es2 [desktop] objects are displayed as black issue**
- [ ] **glmark2 & glamrk2-es2 [ideas] crash issue**
- [ ] **XFCE4 GUI issue**
- [ ] **Shotcut & Kdenlive UI layout appears as black issue**
- [ ] **Firefox & Chromium WebGL crash issue**
- [ ] **Supertuxkart work issue**
- [ ] **Blender not work issue**

These are the issues identified with the `Adreno 740 GPU` and `Adreno 750 GPU`.
Both GPUs exhibit similar symptoms.

<details><summary>glmark2 & glamrk2-es2 [desktop] objects are displayed as black issue</summary>
<p>

A confirmed issue where translucent objects are displayed as black.
For the `Adreno 750 GPU`, the entire screen is displayed as black.

![image](https://github.com/user-attachments/assets/f91d43b4-1312-4f33-a652-1ba8ff81cfcf)
![image](https://github.com/user-attachments/assets/fbc48da5-860f-4ba1-b26c-412c08af9fe9)

</p>
</details> 

<details><summary>glmark2 & glamrk2-es2 [ideas] crash issue</summary>
<p>

In the **[ideas]** benchmark, the following error occurs, causing a crash.
`MESA: error: ZINK: vkCreateGraphicsPipelines failed (VK_ERROR_UNKNOWN)`

```
~$ glmark2
=======================================================
    glmark2 2023.01
=======================================================
    OpenGL Information
    GL_VENDOR:      Mesa
    GL_RENDERER:    zink Vulkan 1.3(Adreno (TM) 740 (QUALCOMM_PROPRIETARY))
    GL_VERSION:     4.6 (Compatibility Profile) Mesa 24.2.3
    Surface Config: buf=32 r=8 g=8 b=8 a=8 depth=24 stencil=0 samples=0
    Surface Size:   800x600 windowed
=======================================================
[build] use-vbo=false: FPS: 653 FrameTime: 1.533 ms
[build] use-vbo=true: FPS: 648 FrameTime: 1.544 ms
[texture] texture-filter=nearest: FPS: 636 FrameTime: 1.573 ms
[texture] texture-filter=linear: FPS: 632 FrameTime: 1.583 ms
[texture] texture-filter=mipmap: FPS: 634 FrameTime: 1.579 ms
[shading] shading=gouraud: FPS: 606 FrameTime: 1.651 ms
[shading] shading=blinn-phong-inf: FPS: 602 FrameTime: 1.663 ms
[shading] shading=phong: FPS: 597 FrameTime: 1.677 ms
[shading] shading=cel: FPS: 585 FrameTime: 1.712 ms
[bump] bump-render=high-poly: FPS: 521 FrameTime: 1.922 ms
[bump] bump-render=normals: FPS: 629 FrameTime: 1.592 ms
[bump] bump-render=height: FPS: 603 FrameTime: 1.659 ms
[effect2d] kernel=0,1,0;1,-4,1;0,1,0;: FPS: 551 FrameTime: 1.816 ms
[effect2d] kernel=1,1,1,1,1;1,1,1,1,1;1,1,1,1,1;: FPS: 494 FrameTime: 2.027 ms
[pulsar] light=false:quads=5:texture=false: FPS: 556 FrameTime: 1.799 ms
[desktop] blur-radius=5:effect=blur:passes=1:separable=true:windows=4: FPS: 277 FrameTime: 3.614 ms
[desktop] effect=shadow:windows=4: FPS: 434 FrameTime: 2.305 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 379 FrameTime: 2.639 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=subdata: FPS: 382 FrameTime: 2.619 ms
[buffer] columns=200:interleave=true:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 429 FrameTime: 2.335 ms
[ideas] speed=duration:MESA: error: ZINK: vkCreateGraphicsPipelines failed (VK_ERROR_UNKNOWN)
Segmentation fault
``` 
```
~$ glmark2-es2
libEGL warning: DRI3: Screen seems not DRI3 capable
=======================================================
    glmark2 2023.01
=======================================================
    OpenGL Information
    GL_VENDOR:      Mesa
    GL_RENDERER:    zink Vulkan 1.3(Adreno (TM) 740 (QUALCOMM_PROPRIETARY))
    GL_VERSION:     OpenGL ES 3.2 Mesa 24.2.3
    Surface Config: buf=32 r=8 g=8 b=8 a=8 depth=24 stencil=0 samples=0
    Surface Size:   800x600 windowed
=======================================================
[build] use-vbo=false: FPS: 738 FrameTime: 1.356 ms
[build] use-vbo=true: FPS: 848 FrameTime: 1.180 ms
[texture] texture-filter=nearest: FPS: 829 FrameTime: 1.207 ms
[texture] texture-filter=linear: FPS: 818 FrameTime: 1.224 ms
[texture] texture-filter=mipmap: FPS: 793 FrameTime: 1.261 ms
[shading] shading=gouraud: FPS: 766 FrameTime: 1.307 ms
[shading] shading=blinn-phong-inf: FPS: 771 FrameTime: 1.298 ms
[shading] shading=phong: FPS: 759 FrameTime: 1.318 ms
[shading] shading=cel: FPS: 749 FrameTime: 1.335 ms
[bump] bump-render=high-poly: FPS: 634 FrameTime: 1.577 ms
[bump] bump-render=normals: FPS: 796 FrameTime: 1.256 ms
[bump] bump-render=height: FPS: 772 FrameTime: 1.297 ms
[effect2d] kernel=0,1,0;1,-4,1;0,1,0;: FPS: 685 FrameTime: 1.461 ms
[effect2d] kernel=1,1,1,1,1;1,1,1,1,1;1,1,1,1,1;: FPS: 597 FrameTime: 1.677 ms
[pulsar] light=false:quads=5:texture=false: FPS: 679 FrameTime: 1.475 ms
[desktop] blur-radius=5:effect=blur:passes=1:separable=true:windows=4: FPS: 299 FrameTime: 3.347 ms
[desktop] effect=shadow:windows=4: FPS: 523 FrameTime: 1.914 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 339 FrameTime: 2.956 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=subdata: FPS: 478 FrameTime: 2.092 ms
[buffer] columns=200:interleave=true:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 424 FrameTime: 2.364 ms
[ideas] speed=duration:MESA: error: ZINK: vkCreateGraphicsPipelines failed (VK_ERROR_UNKNOWN)
Segmentation fault
``` 

</p>
</details> 

<details><summary>XFCE4 GUI issue</summary>
<p>

In the `XFCE4 desktop environment`, some parts of the UI appear broken.
Could this be related to the **glmark2 & glmark2-es2 [desktop] issue**?
![image](https://github.com/user-attachments/assets/d6e97582-fd9c-49ef-b385-738d8a9f8215)

</p>
</details> 

<details><summary>Shotcut & Kdenlive UI layout appears as black issue</summary>
<p>

`Shotcut & Kdenlive` runs, but some parts of the UI layout display as a black screen.
![image](https://github.com/user-attachments/assets/03dabb55-7190-4c4f-ac93-72274cd489f6)
![image](https://github.com/user-attachments/assets/9056ee8e-1e9f-4fc5-b6a1-5da273967b27)

</p>
</details> 

<details><summary>Firefox & Chromium WebGL crash issue</summary>
<p>

When accessing `WebGL` support pages in `Firefox & Chromium` browsers, the browsers crash.

</p>
</details> 

<details><summary>Supertuxkart work issue</summary>
<p>

When running `Supertuxkart`

- On the `Adreno 750 GPU`, only the background is displayed.
![image](https://github.com/user-attachments/assets/3d4f56ba-b0b8-4361-ad5a-8d4f5c255109)

- On the `Adreno 740 GPU`, the UI appears broken, and the game crashes upon entering the gameplay screen.
```
MESA: error: ZINK: vkCreateGraphicsPipelines failed (VK_ERROR_UNKNOWN)
Segmentation fault
``` 
![image](https://github.com/user-attachments/assets/19e15c36-a087-4669-bad5-c3da83c72b12)

</p>
</details> 

<details><summary>Blender not work issue</summary>
<p>

`Blender` does not run and displays the following error.
```
~$ blender
Warning: Falling back to the standard locale ("C")
../src/src/vulkan/wsi/wsi_common_x11.c:1909: Swapchain status changed to VK_SUBOPTIMAL_KHR
MESA: error: ZINK: vkCreateGraphicsPipelines failed (VK_ERROR_UNKNOWN)
Writing: /data/data/com.termux/files/usr/tmp/blender.crash.txt
Segmentation fault
``` 

</p>
</details> 

## Samsung Xclipse series GPU

- [ ] **Blender 3D viewer appears doubled as if mirrored issue**
- [ ] **Shotcut & Kdenlive UI layout appears jumbled issue**
- [ ] **Supertuxkart screen UI is broken, and 3D objects do not display issue**
- [ ] **Firefox & Chromium Unity3D engine-based WebGL game screen corruption issue**

These are issues common to the `Xclipse series GPU`.
They all appear to be similar in nature.

<details><summary>Blender 3D viewer appears doubled as if mirrored issue</summary>
<p>

![image](https://github.com/user-attachments/assets/e19f5c15-a5db-4952-9631-99658acbd187)
![image](https://github.com/user-attachments/assets/c5ee6933-6f13-49a0-819d-74ba558acdfe)

</p>
</details> 

<details><summary>Shotcut & Kdenlive UI layout appears jumbled issue</summary>
<p>

![image](https://github.com/user-attachments/assets/866fd5d9-a5a8-40ec-a0d6-608cc3b43d97)
![image](https://github.com/user-attachments/assets/d55f4829-a6e7-4f55-9252-84f8ccc75224)

</p>
</details> 

<details><summary>Supertuxkart screen UI is broken, and 3D objects do not display issue</summary>
<p>

![image](https://github.com/user-attachments/assets/3aada68f-a081-481c-a6cf-0fac77337929)
![image](https://github.com/user-attachments/assets/a04d44c0-85eb-439a-bedc-253c38478deb)

</p>
</details> 

<details><summary>Firefox & Chromium Unity3D engine-based WebGL game screen corruption issue</summary>
<p>

![image](https://github.com/user-attachments/assets/91cbb68c-62ad-4fd4-b77a-677d98e01c1c)
![image](https://github.com/user-attachments/assets/a1ef6d99-de42-43c6-bfd7-f92a28273787)

</p>
</details>

**Comment by xMeM** [comment]
If the issue still exists after setting the `MESA_VK_WSI_DEBUG=sw,noshm` environment variable, it is not a wrapper issue.

**Comment by hansm629** [comment]
@xMeM 
I tested all items by adding the environment variable `MESA_VK_WSI_DEBUG=sw,noshm`, but the symptoms remain the same.

Unfortunately
It seems that the current state is the limit for the compatibility of SoC manufacturers' `official Vulkan drivers` with `mesa zink`.😔
(`mesa zink` is likely only guaranteed to be compatible with `mesa Turnip` or `mesa RADV`.)

**Comment by 813ethan** [comment]
well this seems to be throwing up in logcat when running glxgears with wrapper, adreno 725
```
11-18 00:55:30.021 27326 27333 I AdrenoVK-0: Shader compilation failed for shaderType: 2
11-18 00:55:30.022 27326 27333 I AdrenoVK-0: Info log: Assertion failed: isa<X>(Val) && "cast<Ty>() argument of incompatible type!"
```
runs fine with llvm or dri3 though
